# Assign workspaces to outputs
workspace = 1,HDMI-A-1
workspace = 2,HDMI-A-1
workspace = 3,HDMI-A-1
workspace = 4,HDMI-A-1
workspace = 5,HDMI-A-1

workspace = 6,eDP-1
workspace = 7,eDP-1
workspace = 8,eDP-1
workspace = 9,eDP-1
workspace = 10,eDP-1
